config/routes.rb
Rails.application.routes.draw do
  resources :links
  #get 'home/index'
  get 'home/about'
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/link.rb
class Link < ApplicationRecord
end

app/models/odkazy.rb
class Odkazy < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
  
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  before_action :set_link, only: %i[ show edit update destroy ]

  # GET /links or /links.json
  def index
    @links = Link.all
  end

  # GET /links/1 or /links/1.json
  def show
  end

  # GET /links/new
  def new
    @link = Link.new
  end

  # GET /links/1/edit
  def edit
  end

  # POST /links or /links.json
  def create
    @link = Link.new(link_params)

    respond_to do |format|
      if @link.save
        format.html { redirect_to link_url(@link), notice: "Link was successfully created." }
        format.json { render :show, status: :created, location: @link }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /links/1 or /links/1.json
  def update
    respond_to do |format|
      if @link.update(link_params)
        format.html { redirect_to link_url(@link), notice: "Link was successfully updated." }
        format.json { render :show, status: :ok, location: @link }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @link.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /links/1 or /links/1.json
  def destroy
    @link.destroy

    respond_to do |format|
      format.html { redirect_to links_url, notice: "Link was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_link
      @link = Link.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def link_params
      params.require(:link).permit(:název_dokumentu, :label, :odkaz)
    end
end

app/controllers/odkazies_controller.rb
class OdkaziesController < ApplicationController
  before_action :set_odkazy, only: %i[ show edit update destroy ]

  # GET /odkazies or /odkazies.json
  def index
    @odkazies = Odkazy.all
  end

  # GET /odkazies/1 or /odkazies/1.json
  def show
  end

  # GET /odkazies/new
  def new
    @odkazy = Odkazy.new
  end

  # GET /odkazies/1/edit
  def edit
  end

  # POST /odkazies or /odkazies.json
  def create
    @odkazy = Odkazy.new(odkazy_params)

    respond_to do |format|
      if @odkazy.save
        format.html { redirect_to odkazy_url(@odkazy), notice: "Odkazy was successfully created." }
        format.json { render :show, status: :created, location: @odkazy }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @odkazy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /odkazies/1 or /odkazies/1.json
  def update
    respond_to do |format|
      if @odkazy.update(odkazy_params)
        format.html { redirect_to odkazy_url(@odkazy), notice: "Odkazy was successfully updated." }
        format.json { render :show, status: :ok, location: @odkazy }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @odkazy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /odkazies/1 or /odkazies/1.json
  def destroy
    @odkazy.destroy

    respond_to do |format|
      format.html { redirect_to odkazies_url, notice: "Odkazy was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_odkazy
      @odkazy = Odkazy.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def odkazy_params
      params.require(:odkazy).permit(:název_dokumentu, :téma, :odkaz)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/links_helper.rb
module LinksHelper
end

app/helpers/odkazies_helper.rb
module OdkaziesHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Uvodni strana', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Databaze', links_path, class:"navbar-brand" %>
        </li>
        <li class="nav-item">
          <%= link_to 'New link', new_link_path, class:"navbar-brand" %>
        </li>

      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>Zde bude databaze</h1>

app/views/home/index.html.erb
<div class="container">
<h1>Uvodni strana</h1>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <title>Zde bude databaze</title>
  <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>
  <body>

  <%= render 'home/header' %>
  <%= yield %>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
    -->
  </body>
</html>

app/views/links/_form.html.erb
<div class="container">
<%= form_with(model: link) do |form| %>
  <% if link.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(link.errors.count, "error") %> prohibited this link from being saved:</h2>

      <ul>
        <% link.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-3">
    <%= form.text_field :název_dokumentu, class:"form-control", placeholder:"Název dokumentu" %>
  </div>

  <div class="field mb-3">
    <%= form.text_field :label, class:"form-control",placeholder:"Téma" %>
  </div>

  <div class="field mb-3">
    <%= form.text_field :odkaz, class:"form-control", placeholder:"Odkaz" %>
  </div>

  <div class="actions">
    <%= form.submit class:'btn btn-light' %>
  </div>
<% end %>

app/views/links/edit.html.erb
<div class="container">
<h1>Editing Link</h1>

<%= render 'form', link: @link %>

<%= link_to 'Show', @link %> |
<%= link_to 'Back', links_path %>

app/views/links/index.html.erb
<p id="notice"><%= notice %></p>

<h2>Odkazy na dokuenty</h2>

<table class='table table-striped table-bordered table-hover'>
  <thead class='thead-dark'>
    <tr>
      <th>Název dokumentu</th>
      <th>Label</th>
      <th>Odkaz</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @links.each do |link| %>
      <tr>
        <td><%= link.název_dokumentu %></td>
        <td><%= link.label %></td>
        <td><%= link.odkaz %></td>
        <td><%= link_to 'Show', link %></td>
        <td><%= link_to 'Edit', edit_link_path(link) %></td>
        <td><%= link_to 'Destroy', link, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Link', new_link_path, class:"btn btn-light" %>

app/views/links/new.html.erb
<h1>Add new link</h1>
<br/>
<%= render 'form', link: @link %>

<%= link_to 'Back', links_path %>

app/views/links/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container-fluid bg-dark text-light p-5">
    <div class="container bg-dark p-5">
        <h1 class="display-4"><%= @link.název_dokumentu %></h1>
        <hr>
        <p><%= @link.label %></p>
        <br/>
        <a href="<%= @link.odkaz %>" class="btn btn-light">link</a>
    </div>
</div>


<%= link_to 'Edit', edit_link_path(@link), class:"btn btn-light" %>
<%= link_to 'Back', links_path, class:"btn btn-light" %>